baseurl:
email: bboe@cs.ucsb.edu
defaults:
  - scope:
      path: ""
    values:
      layout: andreas08
  - scope:
      path: cs32_m12/
    values:
      layout: cs32_m12
  - scope:
      path: cs24_m13/
    values:
      layout: cs24_m13
  - scope:
      path: cs24_f13/
    values:
      layout: cs24_f13

url: https://ucsb.bryceboe.com

# Build settings
plugins:
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
